Repository BCG-X-Official/artkit, pull requests merged in 2024-06, with the labels that each got.

#16 DOC: Add bug report and feature request issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  pull_request_template.md
  sphinx/source/contributor_guide/how_to_contribute.rst
Labels: documentation

#15 BUILD: prepare for next release
  .github/workflows/artkit-release-pipeline.yml
  .github/workflows/pytest.yml
  .github/workflows/python-lint.yml
  condabuild/meta.yaml
  make.py
  pyproject.toml
  src/artkit/__init__.py
  tox.ini
Labels: build

#26 DOC: Miscellaneous cleanups
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  sphinx/source/examples/equitability/bias_detection_with_counterfactual_experiment/notebook.ipynb
Labels: documentation

#25 FIX: Add imports for diffusion and vision cached model classes to `artkit.api`
  RELEASE_NOTES.rst
  src/artkit/model/diffusion/__init__.py
  src/artkit/model/diffusion/_cached.py
  src/artkit/model/diffusion/base/__init__.py
  src/artkit/model/vision/__init__.py
  src/artkit/model/vision/_cached.py
  src/artkit/model/vision/base/__init__.py
  test/artkit_test/model/diffusion/test_diffusion_openai.py
  test/artkit_test/model/vision/test_vision_openai.py
Labels: bug

#27 BUILD: release artkit 1.0.1
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/artkit-release-pipeline.yml
  .github/workflows/pytest.yml
  .github/workflows/python-lint.yml
  CONTRIBUTING.md
  README.rst
  RELEASE_NOTES.rst
  condabuild/meta.yaml
  make.py
  pull_request_template.md
  pyproject.toml
  sphinx/source/contributor_guide/how_to_contribute.rst
  sphinx/source/contributor_guide/setup.rst
  sphinx/source/examples/equitability/bias_detection_with_counterfactual_experiment/notebook.ipynb
  sphinx/source/user_guide/introduction_to_artkit/genai_testing_and_evaluation.rst
  src/artkit/__init__.py
  src/artkit/model/diffusion/__init__.py
  src/artkit/model/diffusion/_cached.py
  src/artkit/model/diffusion/base/__init__.py
  src/artkit/model/vision/__init__.py
  src/artkit/model/vision/_cached.py
  src/artkit/model/vision/base/__init__.py
  test/artkit_test/model/diffusion/test_diffusion_openai.py
  test/artkit_test/model/vision/test_vision_openai.py
  tox.ini
Labels: build

#30 API: Clear cache entries after given create or access time
  sphinx/source/user_guide/advanced_tutorials/cache_management.ipynb
  src/artkit/model/base/_adapter.py
  src/artkit/model/cache/_cache.py
  test/artkit_test/model/cache/test_cache.py
Labels: enhancement

#36 BUILD: Add backward compatibility for Python 3.10
  .github/workflows/artkit-release-pipeline.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  environment.yml
  pypi_description.rst
  pyproject.toml
  sphinx/source/contributor_guide/setup.rst
  src/artkit/model/cache/_cache.py
  src/artkit/model/llm/base/_llm.py
  tox.ini
Labels: build

#38 API: Expose base models in API package
  RELEASE_NOTES.rst
  src/artkit/api.py
  src/artkit/model/llm/base/_llm.py
Labels: enhancement
